#! /bin/sh

# Create MagyArchLinux 2020 <krive@magyarchlinux.org>
# Arch Linux auto-update and loging.

# Check cronie installed.
pacman -Qs cronie > /dev/null
OUTPUT="$?"

pacman -Qs reflector > /dev/null
OUTPUT_2="$?"

if [[ "$OUTPUT_2" -eq 1 ]]
then
    sudo pacman -S reflector --noconfirm
fi

sudo cp cronpacman /usr/bin


if [[ "$OUTPUT" -eq 1 ]]
then
    sudo pacman -S cronie --noconfirm
    sudo systemctl enable cronie.service
    sudo systemctl start cronie.service
    echo -e "\n0 */10 * * * $(which cronpacman)\n" | sudo tee -a /var/spool/cron/root
else
    systemctl list-unit-files --state enabled --type service | grep "cronie" > /dev/null
    OUTPUT_1="$?"
    if [[ "$OUTPUT_1" -eq 1 ]]
    then
        sudo systemctl enable cronie.service
        sudo systemctl start cronie.service
        echo -e "\n0 */10 * * * $(which cronpacman)\n" | sudo tee -a /var/spool/cron/root
    else
        sudo systemctl start cronie.service
        echo -e "\n0 */10 * * * $(which cronpacman)\n" | sudo tee -a /var/spool/cron/root 
    fi
fi
